version: "3.7"

services:
  postgres:
    build:
      dockerfile: pg.Dockerfile
      context: .
    container_name: db
    restart: always
    env_file: .env
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - microservices-network

  server:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: server
    env_file: .env
    depends_on:
      - postgres
    networks:
      - microservices-network
    ports:
      - "3000:3000"

volumes:
  data:
  static:
    driver: local

networks:
  microservices-network:
    driver: bridge